export const SwaggerConstants = {
  Config: {
    API_VERSION: '/v1/api',
  },
  Tag: {
    INFO: 'Info',
    SETTINGS: 'Settings',
    ACCOUNT: 'Account',
    CHART_WIDGET: 'ChartWidget',
    ACCOUNT_CHART_WIDGET: 'AccountChartWidget',
    GAPI_SEARCH: 'GapiSearch',
    GAPI_SEARCH_META: 'GapiSearchMeta',
    AMPQ_ENOBOT_ORDER: 'AmpqEnobotOrder',
    AMPQ_ENOBOT_STRATEGY: 'AmpqEnobotStrategy',
    AMPQ_ENOBOT_CUSTOMER_STRATEGY: 'AmpqEnobotCustomerStrategy',
    CMD_EXCHANGE_LOG: 'CmdExchangeLog',
    STATKRAFT_ENOBOT_REQUEST: 'StatkraftEnobotRequest',
    MULE_ENOBOT_STRATEGY: 'MuleEnobotStrategy',
    MULE_ENOBOT_CUSTOMER_STRATEGY: 'MuleEnobotCustomerStrategy',
    MULE_ENOBOT_REQUEST: 'MuleEnobotRequest',
    MULE_EPEX_META: 'MuleEpexMeta',
    MULE_EPEX_AVG: 'MuleEpexAvg',
    MULE_EPEX_OB_CONTRACT: 'MuleEpexObContract',
    MULE_EPEX_PUBLIC_TRADE_CONTRACT: 'MuleEpexPublicTradeContract',
    HEARTBEATS: 'Heartbeats',
  },
  Example: {
    UUID: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
    SQL_ID: '1',
    NAME: 'Jack London',
    EMAIL: 'jack.london@enovos.eu',
    DATE_TIME: '2021-09-29T09:21:57.006Z',
    DATE_TIME_MS: 1635621217830,
    CUSTOMER: 'TM',
    SIDE: 'RWE',
    NOTE: 'Some notes',
  },
  Description: {
    UNIQUE_ID: 'Unique id',
  },
  Format: {
    UUID: 'uuid',
    SQL_ID: 'sqlid',
    EMAIL: 'email',
    DATE: 'date',
    DATE_TIME: 'date-time',
    PASSWORD: 'password',
    BYTE: 'byte',
    BINARY: 'binary',
    NUMBER: 'number',
  },
  Error: {
    ERROR_MESSAGE: 'Error message',
  },
  Response: {
    OK: 'OK',
    NO_CONTENT: 'No Content',
    CREATED: 'Created',
    NOT_FOUND: 'Not Found',
    UNAUTHORIZED: 'Unauthorized',
    CONFLICT: 'Conflict',
    BAD_REQUEST: 'Bad Request',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    ITEM_ALREADY_EXISTS: 'Item already exists',
  },
};
