#image: node:latest
image: node:12

cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - build
  - deploy
  - security
  - leanix

variables:
  NODE_ENV: 'CI'
  LOG_FOLDER: '.'
  LOG_FILE: 'queries.log'

.caching:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull

before_script:
  - npm ci --cache .npm --prefer-offline --no-audit

test:quality:
  stage: test
  allow_failure: true
  script:
    - npm run lint

test:unit:
  stage: test
  script:
    - npm run test:unit

test:integration:
  stage: test
  script:
    - npm run test:integration

include:
  - project: 'Biz-IT/common/nodejs'
    file:
      - '/ci-configs/dependencies.yaml'
      - '/ci-configs/leanix.yaml'
