@protocol = HTTP/1.1
@host = http://localhost
@port = 8080
@baseUrl = /v1/api/mule/enobotRequests
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json

### findAll
GET {{url}}?delivery_day=2021-05-07 {{protocol}}
Content-Type: {{contentTypeJson}}
