@protocol = HTTP/1.1
@host = http://localhost
@port = 8080
@baseUrl = /v1/api/mule/enobotCustomerStrategies
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json

### findAll
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}
