@protocol = HTTP/1.1
@host = http://localhost
@port = 8080
@baseUrl = /v1/api/users
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json
@entityId = 625c340a362b6e9bbcd44a2f
@authHeader = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVjMjMxODc2OTYxNGQ2ZGM4ODY1OTEiLCJpYXQiOjE2NTAyMDk2NjksImV4cCI6MTY1MDIzODQ2OX0.wHltLfHEiX-jSrImOrFKcZd9Nn0IvaHVjz3o3N0IyhQ

### findAll
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}
Authorization: {{authHeader}}

### findById
GET {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Authorization: {{authHeader}}

### save
POST {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}
Authorization: {{authHeader}}

{
"name": "jdoe1",
"email": "jdoe1@company.com",
"password": "12345678"
}

### updateById
PATCH {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Authorization: {{authHeader}}

{
"name": "jsmith"
}

### deleteById
DELETE {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Authorization: {{authHeader}}
