@protocol = HTTP/1.1
@host = http://localhost
@port = 8080
@baseUrl = /v1/api/products
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json
@contentTypeFormData = multipart/form-data
@entityId = 625d5be99ba8f9fc327c01da
@token = Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVjMjMxODc2OTYxNGQ2ZGM4ODY1OTEiLCJpYXQiOjE2NTAyODU0MTksImV4cCI6MTY1MDMxNDIxOX0.yHaMtz55To5SWCNlpIPCImTHNE7PUGyCa8m0KdR4uD8
@authCookie = Authorization={{token}}; HttpOnly; Max-Age=28800
@authHeader = Bearer {{token}}

### head
HEAD {{url}} {{protocol}}

### head
HEAD {{url}}/{{entityId}} {{protocol}}

### options
OPTIONS {{url}} {{protocol}}

### options
OPTIONS {{url}}/{{entityId}} {{protocol}}

### findAll
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}

### findAll with params
GET {{url}}?keyword=product {{protocol}}
Content-Type: {{contentTypeJson}}

### findAll with a paginator
GET {{url}}?page=1&pageLimit=2 {{protocol}}
Content-Type: {{contentTypeJson}}

### findAll top 3 rated
GET {{url}}?sort=-rating&pageLimit=3 {{protocol}}
Content-Type: {{contentTypeJson}}

### findById
GET {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}

### save
POST {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}
# Authorization: {{authHeader}}

{
    "name": "product1",
    "image": "/assets/images/airpods.jpg",
    "description": "description...",
    "brand": "Apple",
    "category": "Electronics",
    "price": 109.99,
    "countInStock": 12,
    "rating": 4.8,
    "numReviews": 17,
    "user": "625c87192b7e7b72f285fd17"
}

### updateById
PATCH {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
Cookie: {{authCookie}}
# Authorization: {{authHeader}}

{
  "description": "updated description..."
}

### deleteById
DELETE {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}
# Cookie: {{authCookie}}
Authorization: {{authHeader}}

### upload image
POST {{url}}/upload?field=image&imageFileType=true {{protocol}}
Content-Type: {{contentTypeFormData}}
