@protocol = HTTP/1.1
@host = http://localhost
@port = 8080
@baseUrl = /v1/api/files
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json
@contentTypeFormData = multipart/form-data
@entityId = playstation.jpg

### findAll
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}

### findByName (download)
GET {{url}}/{{entityId}} {{protocol}}
Content-Type: {{contentTypeJson}}

### save (upload)
POST {{url}}?field=upload_file&limitFileSize=4&imageFileType=true {{protocol}}
